version: "3.5"

services:
  api1: &api
    image: rhsobr/rinha-de-backend-2024-q1-go:1.0.0-alpine
    hostname: api1
    environment:
      - API_PORT=3000
      - DATABASE_URL=postgres://admin:admin@db:5432/rinha?application_name=%app%
      - DB_MAX_RW_CONNECTIONS=10
      - GIN_MODE=release
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthcheck/ || exit 1
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 128MB
    networks:
      - app_network

  api2:
    <<: *api
    hostname: api2

  nginx:
    image: byjg/nginx-extras
    tty: true
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: service nginx status || exit 1
      interval: 15s
      timeout: 3s
      retries: 2
    ports:
      - 9999:9999
    expose:
      - "9999"
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "16MB"
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./configs/database/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./configs/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    command: postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 256MB
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
